version: "3.1"

services:
  mealie-frontend:
    image: hkotel/mealie:frontend-v1.0.0beta-5
    deploy:
      resources:
        limits:
          memory: 200M
    container_name: mealie-frontend
    environment:
    # Set Frontend ENV Variables Here
      - API_URL=http://mealie-api:9000
    restart: always
    ports:
      - "9925:3000"
    volumes:
      - mealie-data:/app/data/
  
  mealie-api:
    image: hkotel/mealie:api-v1.0.0beta-5
    deploy:
      resources:
        limits:
          memory: 200M
    container_name: mealie-api
    volumes:
      - mealie-data:/app/data/
    environment:
    # Set Backend ENV Variables Here
      - ALLOW_SIGNUP=false
      - PUID=1000
      - PGID=1000
      - TZ=America/Indianapolis
      - MAX_WORKERS=1
      - WEB_CONCURRENCY=1
      - BASE_URL=http://localhost:8081
    restart: always

volumes:
  mealie-data:
    driver: local

networks:
  default:
    name: my-main-net
    external: true
