version: "3.1"

services:
  npm-app:
    image: 'jc21/nginx-proxy-manager:latest'
    container_name: npm-app
    restart: unless-stopped
    ports:
      # Public HTTP Port
      - '80:80'
      # Public HTTPS Port
      - '443:443'
      # Admin Web Port
      - '81:81'
    volumes:
      - ~/nginx-proxy/data:/data
      - ~/nginx-proxy/letsencrypt:/etc/letsencrypt

networks:
  default:
    name: my-main-net
    external: true 
