version: "3.1"

services:
  mealie:
    image: ghcr.io/mealie-recipes/mealie:v1.11.0 # 
    container_name: mealie
    restart: always
    ports:
        - "9925:9000" # 
    deploy:
      resources:
        limits:
          memory: 1000M # 
    volumes:
      - mealie-data:/app/data/
    environment:
      # Set Backend ENV Variables Here
      ALLOW_SIGNUP: false
      PUID: 1000
      PGID: 1000
      TZ: America/Indianapolis
      MAX_WORKERS: 1
      WEB_CONCURRENCY: 1
      BASE_URL: http://localhost:8081
      SMTP_HOST: smtp.gmail.com
      SMTP_PORT: 465
      SMTP_FROM_NAME: Mealie
      SMTP_AUTH_STRATEGY: SSL
      SMTP_FROM_EMAIL: $email
      SMTP_USER: $user
      SMTP_PASSWORD: $password

volumes:
  mealie-data:
    driver: local

networks:
  default:
    name: my-main-net
    external: true
