version: "3.8"
services:
  heimdall:
    image: linuxserver/heimdall
    container_name: heimdall
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - ./config:/config
    ports:
      - 8180:80
      - 8443:443
    restart: unless-stopped

networks:
  default:
    name: my-main-net
    external: true
